### PR TITLE
Demo Fetch Api multiple

### PR DESCRIPTION
**Pull request by duythinh96**
Please help me review this

### CODE REVIEW

**Review by ndthinhsgt — CHANGES_REQUESTED** [review]
Add controller, route, ... please

**Review by ndthinhsgt — CHANGES_REQUESTED** [review]
Update your personal page and add route for new items please

**Review by ndthinhsgt — CHANGES_REQUESTED** [review]
Look good now, please deploy and test on website

**Comment by duythinh96** [comment]
@ndthinhsgt 

Please Approve, Merged is block

**Review by ndthinhsgt — APPROVED** [review]
LGTM !

**Pull request merged**
